name: CI Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-up:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show Docker version
        run: docker --version

      - name: Show Docker Compose version
        run: docker-compose --version

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Stop old containers
        run: docker-compose down

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Show running containers
        run: docker ps
